services:
  - type: web
    name: amex-incentive-calculator
    env: python
    plan: free
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
      python -m spacy download en_core_web_sm
    startCommand: gunicorn --bind 0.0.0.0:$PORT app:app
    envVars:
      - key: FLASK_ENV
        value: production
      - key: FLASK_SECRET_KEY
        generateValue: true
      - key: PYTHONPATH
        value: .
    healthCheckPath: /healthz
    disk:
      name: uploads
      mountPath: /opt/render/project/src/uploads
      sizeGB: 1